- name: Create VLAN on Arista Switch
  hosts: switches
  gather_facts: no
  tasks:
    - name: Ensure VLAN is present
      eos_vlan:
        vlan_id: 100                # Replace with your desired VLAN ID
        name: "VLAN 100"            # Rep lace with your desired VLAN name
        state: present
      register: vlan_result
 
